In [64]:
import jieba
import jieba.analyse
import pandas as pd
import numpy as np
from collections import Counter

In [65]:
import pandas as pd
from collections import Counter
data = pd.read_csv("11101-11103毒品案件資料 .csv")
data

      no type    oc_dt oc_addr        oc_p1 proc_no    kind  weight_g
0     編號   案類     發生日期    發生地點        發生場所一   嫌疑犯人數    毒品品項  數量（淨重）_克
1      1   毒品  1110119  臺南市安南區  公路(省、縣、鄉、鎮道       1    安非他命         0
2      2   毒品  1110131  新北市鶯歌區  公寓(三至五層建築物)       1  甲基安非他命      0.25
3      3   毒品  1110103  新北市鶯歌區  公路(省、縣、鄉、鎮道       1  甲基安非他命         0
4      4   毒品  1110110  基隆市暖暖區  公寓(三至五層建築物)       3      嗎啡         0
..   ...  ...      ...     ...          ...     ...     ...       ...
726  596   毒品  1110102  桃園市中壢區  公寓(三至五層建築物)       1    安非他命      0.24
727  597   毒品  1110106  臺北市內湖區  公路(省、縣、鄉、鎮道       1    安非他命         0
728  598   毒品  1110104  臺北市士林區  公路(省、縣、鄉、鎮道       1    安非他命         0
729  599   毒品  1110218  新北市樹林區  公路(省、縣、鄉、鎮道       1  甲基安非他命      0.36
730  600   毒品  1110215  屏東縣內埔鄉  公路(省、縣、鄉、鎮道       1    安非他命      0.05

[731 rows x 8 columns]

In [66]:
data['seg'] = ""
data['seg1'] = ""
data.head()

   no type    oc_dt oc_addr        oc_p1 proc_no    kind  weight_g seg seg1
0  編號   案類     發生日期    發生地點        發生場所一   嫌疑犯人數    毒品品項  數量（淨重）_克
1   1   毒品  1110119  臺南市安南區  公路(省、縣、鄉、鎮道       1    安非他命         0
2   2   毒品  1110131  新北市鶯歌區  公寓(三至五層建築物)       1  甲基安非他命      0.25
3   3   毒品  1110103  新北市鶯歌區  公路(省、縣、鄉、鎮道       1  甲基安非他命         0
4   4   毒品  1110110  基隆市暖暖區  公寓(三至五層建築物)       3      嗎啡         0

In [67]:
index = 0
for documents in data['oc_addr']:
    seg_list = jieba.analyse.extract_tags(documents, 1500)
    data['seg'].iloc[index] = seg_list
    index += 1

In [68]:
data["seg"]

0            [生地]
1        [南市, 安南]
2       [新北市, 歌區]
3       [新北市, 歌區]
4      [暖暖區, 基隆市]
          ...
726    [桃園市, 中壢區]
727      [北市, 湖區]
728      [北市, 士林]
729    [新北市, 樹林區]
730    [屏東縣, 內埔鄉]
Name: seg, Length: 731, dtype: object

In [69]:
index = 0
for documents in data['weight_g']:
    seg_list = jieba.analyse.extract_tags(documents, 1500)
    data['seg1'].iloc[index] = seg_list
    index += 1

In [70]:
data["seg1"]

0      [數量, 淨重]
1            []
2        [0.25]
3            []
4            []
         ...
726      [0.24]
727          []
728          []
729      [0.36]
730      [0.05]
Name: seg1, Length: 731, dtype: object

In [91]:
placedata_seg_list = data['seg'].tolist()
placedata_seg_lis

NameError: name 'placedata_seg_lis' is not defined

In [85]:
data

,no,type,oc_dt,oc_addr,oc_p1,proc_no,kind,weight_g,seg,seg1
0,編號,案類,發生日期,發生地點,發生場所一,嫌疑犯人數,毒品品項,數量（淨重）_克,[生地],"[數量, 淨重]"
1,1,毒品,1110119,臺南市安南區,公路(省、縣、鄉、鎮道,1,安非他命,0,"[南市, 安南]",[]
2,2,毒品,1110131,新北市鶯歌區,公寓(三至五層建築物),1,甲基安非他命,0.25,"[新北市, 歌區]",[0.25]
3,3,毒品,1110103,新北市鶯歌區,公路(省、縣、鄉、鎮道,1,甲基安非他命,0,"[新北市, 歌區]",[]
4,4,毒品,1110110,基隆市暖暖區,公寓(三至五層建築物),3,嗎啡,0,"[暖暖區, 基隆市]",[]
...,...,...,...,...,...,...,...,...,...,...
726,596,毒品,1110102,桃園市中壢區,公寓(三至五層建築物),1,安非他命,0.24,"[桃園市, 中壢區]",[0.24]
727,597,毒品,1110106,臺北市內湖區,公路(省、縣、鄉、鎮道,1,安非他命,0,"[北市, 湖區]",[]
728,598,毒品,1110104,臺北市士林區,公路(省、縣、鄉、鎮道,1,安非他命,0,"[北市, 士林]",[]
729,599,毒品,1110218,新北市樹林區,公路(省、縣、鄉、鎮道,1,甲基安非他命,0.36,"[新北市, 樹林區]",[0.36]
730,600,毒品,1110215,屏東縣內埔鄉,公路(省、縣、鄉、鎮道,1,安非他命,0.05,"[屏東縣, 內埔鄉]",[0.05]

In [86]:
kdata = data[['oc_addr', 'kind', 'weight_g','seg','seg1']]

In [89]:
output_series = kdata.groupby(['oc_addr'])['seg'].apply(lambda x: ','.join(x)).reset_index()

TypeError: sequence item 0: expected str instance, list found

In [90]:
output_series

     weight_g seg1
0           0    ,
1        0.01    ,
2        0.03    ,
3        0.05    ,
4        0.07    ,
..        ...  ...
305      9.93    ,
306      9.94    ,
307        95    ,
308       952    ,
309  數量（淨重）_克    ,

[310 rows x 2 columns]